export declare enum ExecutionErrorCodes {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  UNEXPECTED_RESPONSE = 'UNEXPECTED_RESPONSE',
  SITE_NOT_AVAILABLE = 'SITE_NOT_AVAILABLE',
}
